[package]
name = "hanson"
version = "0.0.0"
edition = "2021"

[dependencies]
build_html = "2.0"
postgres   = "0.19.2"
tiny_http  = "0.9.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
