site_name: Hanson
site_url: https://ruuda.github.io/hanson/
repo_url: https://github.com/ruuda/hanson
strict: true
theme:
  name: null
  custom_dir: docs/theme
nav:
  - Overview:
    - index: index.md
  - User guide:
    - Assets: assets.md
    - Accounts: accounts.md
    - Transactions: transactions.md
